######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 22 07:03:24 2006
######################################################################

TEMPLATE = app
TARGET = qtgl
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += qtgl.h
SOURCES += main.cpp qtgl.cpp
